name: neyvan-test # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: It's testing of snap system with qt
description: |
    It's very long description...
    It's very long description...
    It's very long description...
    It's very long description...
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
 qt1:
  command: desktop-launch $SNAP/opt/myapp/snap-test
  plugs: [home, unity7, x11]

parts:
 project-files:
  plugin: qmake
  source: .
  qt-version: qt5
  project-files: [snap-test.pro]
  install: |
   install -d $SNAPCRAFT_PART_INSTALL/opt/myapp
   install snap-test $SNAPCRAFT_PART_INSTALL/opt/myapp/snap-test
  after: [integration]

 integration:
  plugin: nil
  stage-packages:
   - libc6
   - libstdc++6
   - libc-bin
  after: [desktop-qt5]
